import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Smartphone Pro X',
    description: 'O mais recente smartphone com tecnologia de ponta, câmera de 108MP e tela AMOLED.',
    longDescription: 'Explore o futuro com o Smartphone Pro X. Equipado com o processador mais rápido do mercado, uma tela Super AMOLED de 6.7 polegadas com taxa de atualização de 120Hz para uma fluidez incrível, e um sistema de câmera tripla com sensor principal de 108MP que captura fotos e vídeos em 8K com detalhes impressionantes. A bateria de 5000mAh garante um dia inteiro de uso intenso, com suporte a carregamento super rápido de 45W. Além disso, conta com 5G, Wi-Fi 6E, e resistência à água e poeira IP68. Desbloqueie com o sensor de digital ultrassônico sob a tela e desfrute do ecossistema completo de aplicativos e serviços.',
    price: 4599.9,
    imageUrls: [
        'https://placehold.co/600x600.png',
        'https://placehold.co/601x601.png',
        'https://placehold.co/602x602.png',
    ],
    "data-ai-hint": 'smartphone device',
    category: 'Eletrônicos',
    subcategory: 'Celulares',
    stock: 15,
    maxInstallments: 12,
    createdAt: '2023-10-26T10:00:00Z',
    paymentCondition: '1ª parcela no ato da entrega e o restante mensalmente.',
  },
  {
    id: '2',
    name: 'Notebook UltraSlim',
    description: 'Leve, potente e perfeito para trabalho e lazer. Processador i7, 16GB RAM, 512GB SSD.',
    longDescription: 'O Notebook UltraSlim redefine a portabilidade sem sacrificar o desempenho. Com um chassi de alumínio unibody, pesa apenas 1.2kg. Sua tela de 14 polegadas com resolução 2.8K e bordas finas oferece uma experiência visual imersiva. O processador Intel Core i7 de última geração, combinado com 16GB de RAM LPDDR5, lida com tarefas pesadas com facilidade. O SSD NVMe de 512GB oferece velocidades de leitura e escrita ultrarrápidas. O teclado retroiluminado e o touchpad de vidro de alta precisão garantem conforto e produtividade.',
    price: 7899.0,
    imageUrls: [
        'https://placehold.co/600x600.png',
        'https://placehold.co/601x601.png',
    ],
    "data-ai-hint": 'laptop computer',
    category: 'Eletrônicos',
    subcategory: 'Notebooks',
    stock: 8,
    maxInstallments: 12,
    createdAt: '2023-10-25T11:00:00Z',
  },
  {
    id: '3',
    name: 'Tênis de Corrida',
    description: 'Conforto e performance para seus treinos. Tecnologia de amortecimento avançada.',
    longDescription: 'Alcance seus objetivos com o Tênis de Corrida Performance. A entressola com espuma de dupla densidade oferece um equilíbrio perfeito entre amortecimento macio e resposta rápida. O cabedal de malha projetada é respirável e oferece suporte onde você mais precisa. A sola de borracha de alta abrasão garante durabilidade e tração em diversas superfícies. Ideal para corredores de todos os níveis, desde treinos diários até maratonas.',
    price: 499.99,
    imageUrls: [
        'https://placehold.co/600x600.png',
        'https://placehold.co/601x601.png',
        'https://placehold.co/602x602.png',
    ],
    "data-ai-hint": 'running shoe',
    category: 'Moda',
    subcategory: 'Calçados',
    stock: 30,
    maxInstallments: 6,
    createdAt: '2023-10-24T12:00:00Z',
  },
  {
    id: '4',
    name: 'Camisa Casual',
    description: 'Estilo e conforto para o dia a dia. Feita com 100% algodão premium.',
    longDescription: 'Uma peça essencial para qualquer guarda-roupa, a Camisa Casual é feita com algodão Pima peruano, conhecido por sua suavidade e durabilidade. O corte moderno se ajusta perfeitamente ao corpo, oferecendo um visual elegante e descontraído. Os botões de madrepérola adicionam um toque de sofisticação. Perfeita para usar sozinha ou sob uma jaqueta.',
    price: 189.9,
    imageUrls: [
        'https://placehold.co/600x600.png',
    ],
    "data-ai-hint": 'casual shirt',
    category: 'Moda',
    subcategory: 'Roupas',
    stock: 50,
    maxInstallments: 3,
    createdAt: '2023-10-23T13:00:00Z',
  },
  {
    id: '5',
    name: 'Sofá 3 Lugares',
    description: 'Design moderno e aconchegante para sua sala. Tecido de linho de alta qualidade.',
    longDescription: 'Transforme sua sala de estar com este sofá de 3 lugares. O design minimalista com linhas retas se adapta a qualquer decoração. A estrutura é de madeira maciça de eucalipto, garantindo robustez. As almofadas do assento e do encosto são preenchidas com espuma de alta densidade e uma camada de plumas, proporcionando um conforto excepcional. O revestimento em tecido de linho é durável e fácil de limpar.',
    price: 2999.0,
    imageUrls: [
        'https://placehold.co/600x600.png',
        'https://placehold.co/601x601.png',
    ],
    "data-ai-hint": 'modern sofa',
    category: 'Casa',
    subcategory: 'Móveis para Sala',
    stock: 5,
    maxInstallments: 10,
    createdAt: '2023-10-22T14:00:00Z',
  },
  {
    id: '6',
    name: 'Mesa de Jantar',
    description: 'Mesa para 6 pessoas com tampo de vidro e base de madeira maciça.',
    longDescription: 'Reúna família e amigos ao redor desta elegante mesa de jantar. O tampo de vidro temperado de 10mm é resistente e fácil de manter, enquanto a base escultural de madeira maciça se torna o ponto focal do ambiente. Com capacidade para acomodar confortavelmente 6 pessoas, é a escolha perfeita para refeições memoráveis.',
    price: 1890.5,
    imageUrls: [
        'https://placehold.co/600x600.png',
    ],
    "data-ai-hint": 'dining table',
    category: 'Casa',
    subcategory: 'Móveis para Cozinha',
    stock: 7,
    maxInstallments: 10,
    createdAt: '2023-10-21T15:00:00Z',
  },
  {
    id: '7',
    name: 'Fone de Ouvido Sem Fio',
    description: 'Cancelamento de ruído ativo e 20 horas de bateria. Qualidade de som imersiva.',
    longDescription: 'Mergulhe na sua música com os Fones de Ouvido Sem Fio Aura. A tecnologia de cancelamento de ruído híbrido bloqueia as distrações externas, permitindo que você se concentre no que importa. Os drivers de 40mm oferecem um som rico e detalhado, com graves profundos e agudos cristalinos. A bateria dura até 20 horas com ANC ativado, e um carregamento rápido de 10 minutos oferece 2 horas de audição. O design ergonômico com almofadas de espuma de memória garante conforto durante todo o dia.',
    price: 899.9,
    imageUrls: [
        'https://placehold.co/600x600.png',
        'https://placehold.co/601x601.png',
        'https://placehold.co/602x602.png',
        'https://placehold.co/603x603.png',
    ],
    "data-ai-hint": 'wireless headphones',
    category: 'Eletrônicos',
    subcategory: 'Acessórios',
    stock: 22,
    maxInstallments: 8,
    createdAt: '2023-10-20T16:00:00Z',
  },
  {
    id: '8',
    name: 'Jaqueta Corta-Vento',
    description: 'Leve e resistente à água, ideal para atividades ao ar livre.',
    longDescription: 'Esteja preparado para qualquer clima com a Jaqueta Corta-Vento. Feita de um tecido de nylon ripstop ultraleve, ela oferece proteção contra o vento e chuva leve sem pesar. Possui capuz ajustável, bolsos com zíper e pode ser compactada em seu próprio bolso, tornando-a perfeita para viagens, trilhas ou para o dia a dia na cidade.',
    price: 349.9,
    imageUrls: [
        'https://placehold.co/600x600.png',
        'https://placehold.co/601x601.png',
    ],
    "data-ai-hint": 'windbreaker jacket',
    category: 'Moda',
    subcategory: 'Roupas',
    stock: 18,
    maxInstallments: 5,
    createdAt: '2023-10-19T17:00:00Z',
  },
  {
    id: '9',
    name: 'Smart TV 4K 55"',
    description: 'Imagens vibrantes e som imersivo com a nova Smart TV 4K de 55 polegadas.',
    longDescription: 'Desfrute de uma experiência de cinema em casa com a Smart TV 4K. A tela de 55 polegadas com resolução 4K UHD e HDR oferece cores mais vivas e um contraste incrível. O sistema de som Dolby Atmos cria um ambiente de áudio tridimensional e imersivo. Acesse seus aplicativos favoritos como Netflix, YouTube e Amazon Prime Video diretamente na TV. Controle tudo por voz com os assistentes virtuais integrados.',
    price: 3299.90,
    imageUrls: ['https://placehold.co/600x600.png', 'https://placehold.co/601x601.png'],
    "data-ai-hint": 'smart tv',
    category: 'Eletrônicos',
    subcategory: 'TVs',
    stock: 12,
    maxInstallments: 12,
    createdAt: '2023-10-18T18:00:00Z',
  },
  {
    id: '10',
    name: 'Geladeira Duplex Frost-Free',
    description: 'Grande capacidade e tecnologia Frost-Free para mais praticidade no seu dia a dia.',
    longDescription: 'A Geladeira Duplex oferece espaço de sobra para armazenar os alimentos de toda a família. Com 450 litros de capacidade, prateleiras de vidro temperado e gavetão de legumes, a organização fica muito mais fácil. A tecnologia Frost-Free evita o acúmulo de gelo, eliminando a necessidade de descongelar. O painel eletrônico externo permite controlar a temperatura sem abrir a porta, economizando energia.',
    price: 4199.00,
    imageUrls: ['https://placehold.co/600x600.png'],
    "data-ai-hint": 'refrigerator kitchen',
    category: 'Eletrodomésticos',
    subcategory: 'Geladeiras',
    stock: 10,
    maxInstallments: 12,
    createdAt: '2023-10-17T19:00:00Z',
  },
  {
    id: '11',
    name: 'Cama Box Casal com Molas Ensacadas',
    description: 'Noites de sono tranquilas e revigorantes com o conforto das molas ensacadas.',
    longDescription: 'Tenha o máximo de conforto com a Cama Box Casal. O sistema de molas ensacadas individualmente se adapta aos contornos do corpo, oferecendo suporte personalizado e evitando a transmissão de movimentos. O tampo em malha com tratamento antiácaro e antialérgico garante um ambiente mais saudável para o seu descanso. A base box de madeira reforçada proporciona estabilidade e durabilidade ao conjunto.',
    price: 2199.90,
    imageUrls: ['https://placehold.co/600x600.png', 'https://placehold.co/601x601.png'],
    "data-ai-hint": 'bed bedroom',
    category: 'Casa',
    subcategory: 'Móveis para Quarto',
    stock: 15,
    maxInstallments: 10,
    createdAt: '2023-10-16T20:00:00Z',
  }
];
