import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Smartphone Pro X',
    description: 'O mais recente smartphone com tecnologia de ponta, câmera de 108MP e tela AMOLED.',
    price: 4599.9,
    imageUrl: 'https://placehold.co/600x600.png',
    "data-ai-hint": 'smartphone device',
    category: 'Eletrônicos',
    stock: 15,
  },
  {
    id: '2',
    name: 'Notebook UltraSlim',
    description: 'Leve, potente e perfeito para trabalho e lazer. Processador i7, 16GB RAM, 512GB SSD.',
    price: 7899.0,
    imageUrl: 'https://placehold.co/600x600.png',
    "data-ai-hint": 'laptop computer',
    category: 'Eletrônicos',
    stock: 8,
  },
  {
    id: '3',
    name: 'Tênis de Corrida',
    description: 'Conforto e performance para seus treinos. Tecnologia de amortecimento avançada.',
    price: 499.99,
    imageUrl: 'https://placehold.co/600x600.png',
    "data-ai-hint": 'running shoe',
    category: 'Moda',
    stock: 30,
  },
  {
    id: '4',
    name: 'Camisa Casual',
    description: 'Estilo e conforto para o dia a dia. Feita com 100% algodão premium.',
    price: 189.9,
    imageUrl: 'https://placehold.co/600x600.png',
    "data-ai-hint": 'casual shirt',
    category: 'Moda',
    stock: 50,
  },
  {
    id: '5',
    name: 'Sofá 3 Lugares',
    description: 'Design moderno e aconchegante para sua sala. Tecido de linho de alta qualidade.',
    price: 2999.0,
    imageUrl: 'https://placehold.co/600x600.png',
    "data-ai-hint": 'modern sofa',
    category: 'Casa',
    stock: 5,
  },
  {
    id: '6',
    name: 'Mesa de Jantar',
    description: 'Mesa para 6 pessoas com tampo de vidro e base de madeira maciça.',
    price: 1890.5,
    imageUrl: 'https://placehold.co/600x600.png',
    "data-ai-hint": 'dining table',
    category: 'Casa',
    stock: 7,
  },
  {
    id: '7',
    name: 'Fone de Ouvido Sem Fio',
    description: 'Cancelamento de ruído ativo e 20 horas de bateria. Qualidade de som imersiva.',
    price: 899.9,
    imageUrl: 'https://placehold.co/600x600.png',
    "data-ai-hint": 'wireless headphones',
    category: 'Eletrônicos',
    stock: 22,
  },
  {
    id: '8',
    name: 'Jaqueta Corta-Vento',
    description: 'Leve e resistente à água, ideal para atividades ao ar livre.',
    price: 349.9,
    imageUrl: 'https://placehold.co/600x600.png',
    "data-ai-hint": 'windbreaker jacket',
    category: 'Moda',
    stock: 18,
  },
];
